# Embed the GLSL shaders from the shaders/ directory into the binary.
# Invoked at build time via: cmake -DOUT_HEADER=... -DOUT_SOURCE=... -DSHADER_ROOT=... -P embed_shaders.cmake
#
# Generates:
#   shaders_generated.h - extern declarations of each shader as a C string
#   shaders_generated.c - the shader sources baked in as string literals

set(SHADERS
    "shader_primitive_vert:primitive.vert"
    "shader_primitive_frag:primitive.frag"
    "shader_grid_vert:grid.vert"
    "shader_grid_frag:grid.frag"
    "shader_blit_vert:blit.vert"
    "shader_blit_frag:blit.frag"
    "shader_ui_vert:ui.vert"
    "shader_ui_frag:ui.frag"
)

set(header_content "/* generated by CMake - do not edit */\n#ifndef SUSTAIN_SHADERS_GENERATED_H\n#define SUSTAIN_SHADERS_GENERATED_H\n\n")
set(source_content "/* generated by CMake - do not edit */\n#include \"shaders_generated.h\"\n")

foreach(pair IN LISTS SHADERS)
    string(REPLACE ":" ";" parts "${pair}")
    list(GET parts 0 NAME)
    list(GET parts 1 FILE)
    file(READ "${SHADER_ROOT}/${FILE}" GLSL)
    string(REPLACE "\r" "" GLSL "${GLSL}")
    string(REPLACE "\\" "\\\\" GLSL "${GLSL}")
    string(REPLACE "\"" "\\\"" GLSL "${GLSL}")
    string(REPLACE "\n" "\\n\"\n\"" GLSL "${GLSL}")
    string(APPEND header_content "extern const char ${NAME}[];\n")
    string(APPEND source_content "const char ${NAME}[] =\n    \"${GLSL}\";\n")
endforeach()

string(APPEND header_content "\n#endif\n")
file(WRITE "${OUT_HEADER}" "${header_content}")
file(WRITE "${OUT_SOURCE}" "${source_content}")
